services:
  app:
    build: .
    container_name: project-manager-pro-app
    ports:
      - 4000:4000
    develop:
      watch:
        - path: ./src
          target: /project-manager-pro-app/src
          action: sync
        - path: ./package.json
          action: rebuild
